{% set name = "mlflow-adsp" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data.get('version').lstrip('v') }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  entry_points:
    - mlflow.project_backend = adsp=mlflow_adsp:adsp_backend_builder

requirements:
  host:
    - python>=3.8
    - setuptools
    - versioneer
  run:
    - python>=3.8
    - mlflow>=2.3.0
    - tqdm
    - ae5-tools>=0.7,<1.0
    - psutil
    - pydantic>=2.0,<3
    - click
    - requests

about:
  home: https://github.com/Anaconda-Platform/mlflow-adsp
  summary: "MLFlow Plugin For The Anaconda Data Science Platform"
  license: Apache-2.0
  license_file: LICENSE

test:
  source_files:
    - test
